### ISSUE TITLE
Plugin TV5 - no attribute 'PLAYER_CORE_DVDPLAYER' with Krypton

### ISSUE THREAD

**Issue by slaadvak** [anisite/DepotQuebec#2]
J'utilise libreELEC version 7.90.010 avec  Kodi v17.0-beta7.

Lorsque je veux jouer un vidéo dans le plugin de TV5, ça échoue avec ceci dans mes logs:
```
22:57:26.721 T:1475031968   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'PLAYER_CORE_DVDPLAYER'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.tv5.quebec-canada/default.py", line 570, in <module>
                                                jouer_video(URL)
                                              File "/storage/.kodi/addons/plugin.video.tv5.quebec-canada/default.py", line 341, in jouer_video
                                                xbmc.Player(xbmc.PLAYER_CORE_DVDPLAYER).play(playlist)
                                            AttributeError: 'module' object has no attribute 'PLAYER_CORE_DVDPLAYER'
                                            -->End of Python script error report<--

```

Il suffit de remplacer la ligne 341 dans default.py de ceci:
```
xbmc.Player(xbmc.PLAYER_CORE_DVDPLAYER).play(playlist)
```
vers ceci:
```
xbmc.Player().play(playlist)
```

J'ai testé avec la modif sous Kodi 16.1 sous Windows 10 et ça fonctionne parfaitement.

**Comment by dualB** [comment]
Ça sera réglé.

**Comment by Jimbodeer** [comment]
Même problème dans le add-on de unistv ligne 515

**Comment by dualB** [comment]
Le problème est corrigé, mais j'ai de la difficulté à tester. En attendant, je te suggère de faire la correction manuellement.

**Comment by dualB** [comment]
C'est réglé, et déposé sur Dépôt Québec.
