### ISSUE TITLE
Probleme d'ouverture tou.tv

### ISSUE THREAD

**Issue by zoneamick** [anisite/DepotQuebec#35]
J'ai un souci depuis quelques jours impossible pour moi d'ouvrir ici tou.tv

j'ai désinstaller, reinstaller essayer sur un autre kodi

2019-04-24 21:21:43.623 T:8676   ERROR: Traceback (most recent call last):
2019-04-24 21:21:43.623 T:8676   ERROR:   File "MYPATH\AppData\Roaming\Kodi\addons\plugin.infologique.tou.tv\resources\lib\toutv.py", line 358, in _add_directory_root_extra
2019-04-24 21:21:43.624 T:8676   ERROR:     sections = json.loads(sections)
2019-04-24 21:21:43.624 T:8676   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
2019-04-24 21:21:43.624 T:8676   ERROR:     return _default_decoder.decode(s)
2019-04-24 21:21:43.624 T:8676   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
2019-04-24 21:21:43.624 T:8676   ERROR:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2019-04-24 21:21:43.624 T:8676   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
2019-04-24 21:21:43.624 T:8676   ERROR:     raise ValueError("No JSON object could be decoded")
2019-04-24 21:21:43.624 T:8676   ERROR: ValueError: No JSON object could be decoded
2019-04-24 21:21:43.624 T:8020   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.infologique.tou.tv/
2019-04-24 21:21:43.632 T:19500   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.infologique.tou.tv/) failed
2019-04-24 21:21:46.946 T:8572   ERROR: Traceback (most recent call last):
2019-04-24 21:21:46.946 T:8572   ERROR:   File "MYPATH\AppData\Roaming\Kodi\addons\plugin.infologique.tou.tv\resources\lib\toutv.py", line 358, in _add_directory_root_extra
2019-04-24 21:21:46.947 T:8572   ERROR:     sections = json.loads(sections)
2019-04-24 21:21:46.947 T:8572   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
2019-04-24 21:21:46.947 T:8572   ERROR:     return _default_decoder.decode(s)
2019-04-24 21:21:46.947 T:8572   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
2019-04-24 21:21:46.947 T:8572   ERROR:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2019-04-24 21:21:46.947 T:8572   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
2019-04-24 21:21:46.947 T:8572   ERROR:     raise ValueError("No JSON object could be decoded")
2019-04-24 21:21:46.947 T:8572   ERROR: ValueError: No JSON object could be decoded
2019-04-24 21:21:46.947 T:18652   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.infologique.tou.tv/
2019-04-24 21:21:46.951 T:19500   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.infologique.tou.tv/) failed

**Comment by anisite** [comment]
Merci c'est pris en charge ici 

https://github.com/anisite/plugin.infologique.tou.tv/issues/5#issuecomment-486473221
