### ISSUE TITLE
Tou.tv - erreur avec kodi18

### ISSUE THREAD

**Issue by lpther** [anisite/DepotQuebec#40]
Arrives depuis une semaine environ. Au moment de lister les comédies, avec un tou.tv extra, ça affiche une erreur dans le plugin. Voici le contenu du log:

2019-06-10 20:02:35.449 T:1369948896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 401: Unauthorized
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.infologique.tou.tv/default.py", line 3, in <module>
                                                Main()
                                              File "/home/osmc/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 285, in __init__
                                                self._add_api_url()
                                              File "/home/osmc/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 607, in _add_api_url
                                                toutesEmissions = json.loads(scraper.CALL_HTML_AUTH('https://services.radio-canada.ca/toutv/presentation/search?includeMedias=false&device=web&version=4', 'GET', None, 'client-key <redacted_out>' ))
                                              File "/home/osmc/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutvapiservice.py", line 254, in CALL_HTML_AUTH
                                                response = opener.open(request)
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 401: Unauthorized
                                            -->End of Python script error report<--
2019-06-10 20:02:35.902 T:1353163488   ERROR: GetDirectory - Error getting plugin://plugin.infologique.tou.tv/?folder=%22%20%2f%20Com%c3%a9die%22&url=%22%2fCategory%2fcomedie%22
2019-06-10 20:02:35.908 T:1916208688   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.infologique.tou.tv/?folder=%22%20%2f%20Com%c3%a9die%22&url=%22%2fCategory%2fcomedie%22) failed

**Comment by erikatremblay** [comment]
Je confirme moi aussi tou.tv ne fonctionne plus du tout et j’ai un compte extra

**Comment by benopto** [comment]
Même chose ici. A cessé de fonctionner depuis une semaine. Je n'arrive ni à lancer les vidéos ni à parcourir les répertoires. Je suis sur CoreElec (Kodi 18.2).

**Comment by anisite** [comment]
La version 4.0.4 de ce soir adresse ce problème

**Comment by lpther** [comment]
Testé et ça fonctionne!

Merci!
