### ISSUE TITLE
TVA ne fonctionne pas sur Raspberry pi

### ISSUE THREAD

**Issue by TNT5788** [anisite/DepotQuebec#45]
Bonjour et merci pour votre extension TVA.  L'extension TVA fonctionne bien sur mon portable avec Windows 10 mais elle ne fonctionne pas sur ma Raspberry pi 3.  J'ai la version Lea 18.2 de Kodi et ma Raspberry Pi est sur Raspbian stretch.  Lorsque je démarre l'application TVA j'appuie sur accueil ensuite je choisi un émission ensuite à voir et à revoir et l'épisode.  En choisissant l'épisode j'obtiens l'erreur suivante: 
**TVA Erreur
consultez le journal pour plus d'informations.**

Voici l'erreur dans mes logs:
2019-09-16 17:44:33.136 T:1693422304   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.infologique.TVAgo/default.py", line 105, in <module>
                                                navig.PlayVideo(SOURCE_URL)
                                              File "/home/pi/.kodi/addons/plugin.infologique.TVAgo/resources/lib/navig.py", line 114, in PlayVideo
                                                jsonData = simplejson.loads(html.get_url_txt(strURL, True))
                                              File "/home/pi/.kodi/addons/plugin.infologique.TVAgo/resources/lib/html.py", line 30, in get_url_txt
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--
2019-09-16 17:44:33.258 T:1901732704   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.infologique.TVAgo/?url=url&sourceUrl=6084352463001]
2019-09-16 17:44:45.795 T:1901732704  NOTICE: Stopping player
2019-09-16 17:44:45.795 T:1901732704  NOTICE: Storing total System Uptime

Est-ce que vous seriez en mesure de m'aider avec cette erreur ?

Merci beaucoup,

**Comment by anisite** [comment]
Il n'y a presque pas d'intérêt pour tva au sein de l'équipe dépôt Québec, a moins de se faire proposer un pull request, il y a peu de chance que ce problème soit pris en charge, malheureusement

**Comment by MaximeLussier** [comment]
@anisite @TNT5788 Moi je le maintien pour un collègue qui l'utilise... J'ai fais des changements pour la v1.0.4 qui pourrait corriger ton problème.
