### ISSUE TITLE
UnisTv et  TV5 Québec ne fonctionnent plus

### ISSUE THREAD

**Issue by Sphinxroot** [anisite/DepotQuebec#55]
2020-04-12 14:03:35.020 T:9572   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Usager\AppData\Roaming\Kodi\addons\plugin.video.TV5QuebecCanada\default.py", line 586, in <module>
                                                creer_liste_videos_orphelines(URL, 'listing-carousel-inner')
                                              File "C:\Users\Usager\AppData\Roaming\Kodi\addons\plugin.video.TV5QuebecCanada\default.py", line 207, in creer_liste_videos_orphelines
                                                container = re.split('<div class="pagination-block', container[1])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-04-12 14:03:35.047 T:620   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.TV5QuebecCanada/?mode=6&name=A%20%25C3%25A0%20Z%20-%20Toutes%20les%20vid%25C3%25A9os&url=http%3a%2f%2ftv5.ca%2fvideos%3foptions%5bsort%5d%3dtitle%26options%5border%5d%3dASC%26options%5bpage%5d%3d1
2020-04-12 14:03:35.062 T:7968   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.TV5QuebecCanada/?mode=6&name=A%20%25C3%25A0%20Z%20-%20Toutes%20les%20vid%25C3%25A9os&url=http%3a%2f%2ftv5.ca%2fvideos%3foptions%5bsort%5d%3dtitle%26options%5border%5d%3dASC%26options%5bpage%5d%3d1) failed
2020-04-12 14:03:38.589 T:7968   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-04-12 14:03:39.659 T:5252   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Usager\AppData\Roaming\Kodi\addons\plugin.video.unisTV\default.py", line 597, in <module>
                                                creer_liste_videos_orphelines(URL, 'listing-carousel-inner')
                                              File "C:\Users\Usager\AppData\Roaming\Kodi\addons\plugin.video.unisTV\default.py", line 206, in creer_liste_videos_orphelines
                                                container = re.split('<div class="pagination-block', container[1])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-04-12 14:03:39.687 T:10860   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.unisTV/?mode=6&name=A%20%25C3%25A0%20Z%20-%20Toutes%20les%20vid%25C3%25A9os&url=http%3a%2f%2funis.ca%2fvideos%3foptions%5bsort%5d%3dtitle%26options%5border%5d%3dASC%26options%5bpage%5d%3d1
2020-04-12 14:03:39.695 T:7968   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.unisTV/?mode=6&name=A%20%25C3%25A0%20Z%20-%20Toutes%20les%20vid%25C3%25A9os&url=http%3a%2f%2funis.ca%2fvideos%3foptions%5bsort%5d%3dtitle%26options%5border%5d%3dASC%26options%5bpage%5d%3d1) failed

**Comment by dualB** [comment]
UnisTV et TV5 Québec ne sont plus entretenus, faute de développeur intéressé.

**Comment by Sphinxroot** [comment]
si c est possible j aimerais entrer en communication .. je pourrai donner un coup de main  vue que les sites ont ete join en 1 seul .. sois y a moyen de changer une sources pour l adapter a moin que la structure du site a complement changer versus les anciens ... semblerais que seulement le caroussel ne fonctionne plus :)

**Comment by dualB** [comment]
L'additiel date de plusieurs années et récoltait l'information via la page web des sites concernées. Il faudra réécrire l'ensemble de celui-ci pour interroger plutôt l'API (plus stable) de Unis et TV5-Québec.

**Comment by dualB** [comment]
api.tv5unis.ca

**Comment by dualB** [comment]
Les deux additiels seront retirés, faute de support pour les développer.
