### ISSUE TITLE
tv5 error

### ISSUE THREAD

**Issue by janolapin2016** [anisite/DepotQuebec#6]
le addon tv5 quebec ne fonctionne plus ni sur krypton ni sur jarvis helppppppppppp !!!!!!!

**Comment by dualB** [comment]
As-tu un peu plus de détails sur ce qui ne fonctionne plus?

**Comment by janolapin2016** [comment]
Sur trois machines différentes et avec plusieurs versions de KODI SPMC FTMC Krypton ou Jarvis, une tablette un telephone cellulaire Android et une box TV lorsque je selectionne l'emission que je veux regarder j'ai une erreur qui me renvoie au fichier log. Si je regarde le fichier log du telephone de la tablette ou de la BoxTV Android je vois une erreur relié à "Python Script expected string or buffer" ou "unsupported protocol(plugin) in plugin://plugin.video.TV5QuebecCanada......." etc. 

Maintenant si j'installe KODI portable Krypton 17.3 dans Microsoft Windows 10 ainsi que la source de TV5 puis le addon TV5 Quebec j'ai les mêmes erreurs et dans le log je peux voir Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected string or buffer
                                            Traceback (most recent call last):
                                              File "C:\Users\michel\Desktop\KodiPortable\App\Kodi\portable_data\addons\plugin.video.TV5QuebecCanada\default.py", line 577, in <module>
                                                jouer_video(URL)
                                              File "C:\Users\michel\Desktop\KodiPortable\App\Kodi\portable_data\addons\plugin.video.TV5QuebecCanada\default.py", line 304, in jouer_video
                                                'http://production.ps.delve.cust.lldns.net/r/PlaylistService/media/%s/getPlaylistByMediaId' % media_uid\
                                              File "C:\Users\michel\Desktop\KodiPortable\App\Kodi\portable_data\addons\script.module.simplejson\lib\simplejson\__init__.py", line 488, in loads
                                                return _default_decoder.decode(s)
                                              File "C:\Users\michel\Desktop\KodiPortable\App\Kodi\portable_data\addons\script.module.simplejson\lib\simplejson\decoder.py", line 370, in decode
                                                obj, end = self.raw_decode(s)
                                              File "C:\Users\michel\Desktop\KodiPortable\App\Kodi\portable_data\addons\script.module.simplejson\lib\simplejson\decoder.py", line 389, in raw_decode
                                                return self.scan_once(s, idx=_w(s, idx).end())
                                            TypeError: expected string or buffer
                                            -->End of Python script error report<--

le problème survient sur plusieurs appareils et systèmes différents, c'est donc généralisé et non pas qu'à moi ?

**Comment by janolapin2016** [comment]
Ce n'est pas suffisant comme détails ?

**Comment by dualB** [comment]
Je suis en vacances, je trouve du temps pour faire les correctifs quand je peux.

Une nouvelle version a été déposée sur Dépôt-Québec, ça devrait se mettre à jour automatiquement d'ici peu.

**Comment by janolapin2016** [comment]
ok je pensais que je n'avais pas assez donné de détails... cool merci infiniment
