### ISSUE TITLE
403 forbidden errors pour TVA et TOU.TV

### ISSUE THREAD

**Issue by motosba** [anisite/DepotQuebec#77]
TVA
---------------------------------------------
DEBUG: [TVA+ - DEBUG]: Accessing: https://edge.api.brightcove.com/playback/v1/accounts/5813221784001/videos/ref:tva_6224868479001
DEBUG: CAddonSettings[plugin.infologique.TVAgo]: loading setting definitions
DEBUG: CAddonSettings[plugin.infologique.TVAgo]: trying to load setting definitions from old format...
DEBUG: CAddonSettings[plugin.infologique.TVAgo]: loading setting values
DEBUG: [TVA+ - DEBUG]: html.get_url_txt
DEBUG: CAddonSettings[plugin.infologique.TVAgo]: loading setting definitions
DEBUG: CAddonSettings[plugin.infologique.TVAgo]: trying to load setting definitions from old format...
DEBUG: CAddonSettings[plugin.infologique.TVAgo]: loading setting values
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'urllib2.HTTPError'>
Error Contents: HTTP Error 403: Forbidden
Traceback (most recent call last):
File "/home/user/.kodi/addons/plugin.infologique.TVAgo/default.py", line 116, in <module>
navig.PlayVideo(SOURCE_URL)
File "/home/user/.kodi/addons/plugin.infologique.TVAgo/resources/lib/navig.py", line 149, in PlayVideo
jsonData = simplejson.loads(html.get_url_txt(strURL, True))
File "/home/user/.kodi/addons/plugin.infologique.TVAgo/resources/lib/html.py", line 73, in get_url_txt
response = urlopen(req)
File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python2.7/urllib2.py", line 435, in open
response = meth(req, response)
File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib/python2.7/urllib2.py", line 473, in error
return self._call_chain(*args)
File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
result = func(*args)
File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
-->End of Python script error report<--

TOU.TV avec compte configuré
---------------------------------------------
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'urllib2.HTTPError'>
Error Contents: HTTP Error 403: Forbidden
Traceback (most recent call last):
File "/home/user/.kodi/addons/plugin.infologique.tou.tv/default.py", line 1, in <module>
from resources.lib.toutv import Main
File "/home/user/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 53, in <module>
LOGIN             = scraper.CheckLogged()
File "/home/user/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutvapiservice.py", line 187, in CheckLogged
user()
File "/home/user/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutvapiservice.py", line 303, in user
content = CALL_HTML_AUTH('https://services.radio-canada.ca/toutv/profiling/accounts/login?device=web&version=4',"POST", json.dumps(POST), "client-key " + clientKey)
File "/home/user/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutvapiservice.py", line 248, in CALL_HTML_AUTH
response = opener.open(request)
File "/usr/lib/python2.7/urllib2.py", line 435, in open
response = meth(req, response)
File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib/python2.7/urllib2.py", line 473, in error
return self._call_chain(*args)
File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
result = func(*args)
File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
-->End of Python script error report<--

**Comment by anisite** [comment]
Est-ce que c'est lié à un proxy, un vpn ou autre ? je n'arrive pas à reproduire.

**Comment by phildespres** [comment]
Même erreur ici avec tou.tv. Relié au popup d'acceptation de cookie?

**Comment by phildespres** [comment]
2021-09-26 14:15:29.300 T:140202951444224   ERROR: GetDirectory - Error getting plugin://plugin.infologique.tou.tv/?Key=%22media-2425224169%22&emissionIdExtra=%22%2finfoman%2fS22E02%22
2021-09-26 14:15:29.310 T:140205014987648   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.infologique.tou.tv/?Key=%22media-2425224169%22&emissionIdExtra=%22%2finfoman%2fS22E02%22) failed
2021-09-26 14:18:18.991 T:140203261540096   ERROR: Traceback (most recent call last):
2021-09-26 14:18:18.991 T:140203261540096   ERROR:   File "/home/kodi/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 722, in _add_directory_episodesExtra
2021-09-26 14:18:18.991 T:140203261540096   ERROR:     playStatus = scraper.CALL_HTML_AUTH('https://services.radio-canada.ca/toutv/profiling/playbackstatus' + emissionId + '?device=phone_android&version=4')
2021-09-26 14:18:18.991 T:140203261540096   ERROR:   File "/home/kodi/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutvapiservice.py", line 248, in CALL_HTML_AUTH
2021-09-26 14:18:18.992 T:140203261540096   ERROR:     response = opener.open(request)
2021-09-26 14:18:18.992 T:140203261540096   ERROR:   File "/usr/lib64/python2.7/urllib2.py", line 435, in open
2021-09-26 14:18:18.992 T:140203261540096   ERROR:     response = meth(req, response)
2021-09-26 14:18:18.992 T:140203261540096   ERROR:   File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
2021-09-26 14:18:18.992 T:140203261540096   ERROR:     'http', request, response, code, msg, hdrs)
2021-09-26 14:18:18.992 T:140203261540096   ERROR:   File "/usr/lib64/python2.7/urllib2.py", line 473, in error
2021-09-26 14:18:18.992 T:140203261540096   ERROR:     return self._call_chain(*args)
2021-09-26 14:18:18.992 T:140203261540096   ERROR:   File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
2021-09-26 14:18:18.992 T:140203261540096   ERROR:     result = func(*args)
2021-09-26 14:18:18.992 T:140203261540096   ERROR:   File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
2021-09-26 14:18:18.992 T:140203261540096   ERROR:     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
2021-09-26 14:18:18.992 T:140203261540096   ERROR: HTTPError: HTTP Error 401: Unauthorized
2021-09-26 14:18:19.046 T:140203136812800   ERROR: GetDirectory - Error getting plugin://plugin.infologique.tou.tv/?Key=%22media-2425224169%22&emissionIdExtra=%22%2finfoman%2fS22E02%22
2021-09-26 14:18:19.052 T:140205014987648   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.infologique.tou.tv/?Key=%22media-2425224169%22&emissionIdExtra=%22%2finfoman%2fS22E02%22) failed

**Comment by motosba** [comment]
@anisite oui, l'erreur 403 survient lorsque connecté à un VPN (testé avec ProtonVPN et Mullvad). TVA semble fonctionnel après de nouveaux tests.

**Comment by motosba** [comment]
Also getting 503 errors without VPN :
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'urllib2.HTTPError'>
Error Contents: HTTP Error 503: Service Unavailable
Traceback (most recent call last):
File "/home/user/.kodi/addons/plugin.infologique.tou.tv/default.py", line 1, in <module>
from resources.lib.toutv import Main
File "/home/user/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 53, in <module>
LOGIN             = scraper.CheckLogged()
File "/home/user/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutvapiservice.py", line 187, in CheckLogged
TEST()
File "/home/user/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutvapiservice.py", line 303, in TEST
content = CALL_HTML_AUTH('https://services.radio-canada.ca/toutv/profiling/accounts/login?device=web&version=4',"POST", json.dumps(POST), "client-key " + clientKey)
File "/home/user/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutvapiservice.py", line 248, in CALL_HTML_AUTH
response = opener.open(request)
File "/usr/lib/python2.7/urllib2.py", line 435, in open
response = meth(req, response)
File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib/python2.7/urllib2.py", line 473, in error
return self._call_chain(*args)
File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
result = func(*args)
File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
-->End of Python script error report<--

**Comment by anisite** [comment]
Duplicate https://github.com/anisite/DepotQuebec/issues/78
